/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import button.Button;
import cellAdmin.TableActionCellRender;
import cellAdmin.TableActionCellEditor;
import cellAdmin.TableActionEvent;
import combo_suggestion.ComboBoxSuggestion;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import database.DB;
import server.ServerClient;
import table.TableCustom;

/**
 *
 * @author Rafeed
 */
public class OrderRequestForm extends javax.swing.JPanel implements RefreshButtonFunction {

    private ServerClient client;
    /**
     * Creates new form OrderRequestForm
     */
    public OrderRequestForm() {
        initComponents();
    }
    
    public OrderRequestForm(ServerClient client) {
        this();
        this.client = client;
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        TableActionEvent event = (int row) -> {
            JRadioButton pendingBtn = new JRadioButton("Hold", true);
            JRadioButton acceptBtn = new JRadioButton("Accept");
            JRadioButton declineButton = new JRadioButton("Decline");
            ButtonGroup bgroup = new ButtonGroup();
            bgroup.add(pendingBtn);
            bgroup.add(acceptBtn);
            bgroup.add(declineButton);
            JLabel label = new JLabel("What do want to do with this order?");
            label.setFont(new Font("SansSerif", Font.BOLD, 14));
            final JComponent[] inputs = new JComponent[]{
                label,
                pendingBtn,
                acceptBtn,
                declineButton};
            int result = JOptionPane.showConfirmDialog(null, inputs, "Respond Request", JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                if (acceptBtn.isSelected()) {
                    try {
                        client.sendRequest("RESPOND_ORDER", jTable1.getModel().getValueAt(row, 0).toString(), jTable1.getModel().getValueAt(row, 1).toString(), "accepted");
                        if ("ORDER_ACCEPTED_SUCCESSFULLY".equals(client.getResponse())) {
                            showOrderRequest();
                        } else if ("ORDER_ACCEPT_FAILED".equals(client.getResponse())) {
                            JOptionPane.showMessageDialog(null, "Failed to accept request. Product stock is lower than requested.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(OrderRequestForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (declineButton.isSelected()) {
                    try {
                        client.sendRequest("RESPOND_ORDER", jTable1.getModel().getValueAt(row, 0).toString(), jTable1.getModel().getValueAt(row, 1).toString(), "declined");
                        if ("ORDER_DECLINED_SUCCESSFULLY".equals(client.getResponse())) {
                            showOrderRequest();
                        } else if ("ORDER_DECLINE_FAILED".equals(client.getResponse())) {
                            JOptionPane.showMessageDialog(null, "Failed to execute operation.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(OrderRequestForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        jTable1.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));
        showOrderRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollButton1 = new table.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Product Name", "Quantity", "Date", "Branch", "Action"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private table.TableScrollButton tableScrollButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        showOrderRequest();
    }
    
    private ArrayList<Order> orderRequestList() {
        ArrayList<Order> list = new ArrayList<>();
        try {
            ResultSet rs = new DB().executeQuery("SELECT * FROM ActiveUserRequest WHERE Status = 'pending' ORDER BY OrderID DESC");
            Order order;
            while (rs.next()) {
                order = new Order(rs.getInt("OrderID"), rs.getInt("ProductID"), rs.getInt("Quantity"), rs.getDouble("Price"), rs.getString("Date"), rs.getString("Status"), rs.getInt("BranchID"));
                list.add(order);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderRequestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }

    private void showOrderRequest() {
        ArrayList<Order> orderRequests = orderRequestList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Object[] row = new Object[5];
        for (int i = 0; i < orderRequests.size(); i++) {
            row[0] = orderRequests.get(i).getOrderID();
            row[1] = orderRequests.get(i).getProductName();
            row[2] = orderRequests.get(i).getQuantity();
            row[3] = orderRequests.get(i).getDate();
            row[4] = orderRequests.get(i).getBranchName();
            model.addRow(row);
        }
    }
}
